let customerData = {
  Male: [
    {
      customerID: "C001",
      customerNIC: "933394050V",
      fName: "Kamal",
      lName: "Perera",
      email: "kamal.perera@gmail.com",
      primaryContact: "0711234567",
      secondaryContact: "0771234567",
      address: "No. 12, Temple Road, Colombo 7",
      city: "Colombo",
      joinDate: "2023-01-15",
      img: "../image/customer icon/men.png",
    },
    {
      customerID: "C002",
      customerNIC: "911234567V",
      fName: "Nimal",
      lName: "Silva",
      email: "nimal.silva@gmail.com",
      primaryContact: "0712345678",
      secondaryContact: "0772345678",
      address: "No. 45, Main Street, Kandy",
      city: "Kandy",
      joinDate: "2023-02-12",
      img: "../image/customer icon/men.png",
    },
    {
      customerID: "C003",
      customerNIC: "921234567V",
      fName: "Sunil",
      lName: "Fernando",
      email: "sunil.fernando@gmail.com",
      primaryContact: "0723456789",
      secondaryContact: "0763456789",
      address: "No. 89, Beach Road, Galle",
      city: "Galle",
      joinDate: "2023-03-10",
      img: "../image/customer icon/men.png",
    },
    {
      customerID: "C004",
      customerNIC: "931234567V",
      fName: "Chathura",
      lName: "Wijesinghe",
      email: "chathura.wijesinghe@gmail.com",
      primaryContact: "0714567890",
      secondaryContact: "0754567890",
      address: "No. 67, Lake View, Nuwara Eliya",
      city: "Nuwara Eliya",
      joinDate: "2023-04-25",
      img: "../image/customer icon/men.png",
    },
    {
      customerID: "C005",
      customerNIC: "941234567V",
      fName: "Rohan",
      lName: "Jayawardena",
      email: "rohan.jayawardena@gmail.com",
      primaryContact: "0705678901",
      secondaryContact: "0765678901",
      address: "No. 34, Hill Top, Ratnapura",
      city: "Ratnapura",
      joinDate: "2023-05-20",
      img: "../image/customer icon/men.png",
    },
    {
      customerID: "C006",
      customerNIC: "951234567V",
      fName: "Sanjaya",
      lName: "Abeywickrama",
      email: "sanjaya.abeywickrama@gmail.com",
      primaryContact: "0716789012",
      secondaryContact: "0766789012",
      address: "No. 23, Railway Avenue, Matara",
      city: "Matara",
      joinDate: "2023-06-18",
      img: "../image/customer icon/men.png",
    },
    {
      customerID: "C007",
      customerNIC: "961234567V",
      fName: "Tharindu",
      lName: "Kumara",
      email: "tharindu.kumara@gmail.com",
      primaryContact: "0707890123",
      secondaryContact: "0767890123",
      address: "No. 88, Temple Lane, Kurunegala",
      city: "Kurunegala",
      joinDate: "2023-07-20",
      img: "../image/customer icon/men.png",
    },
    {
      customerID: "C008",
      customerNIC: "971234567V",
      fName: "Kasun",
      lName: "Dissanayake",
      email: "kasun.dissanayake@gmail.com",
      primaryContact: "0718901234",
      secondaryContact: "0768901234",
      address: "No. 14, Seaside Road, Negombo",
      city: "Negombo",
      joinDate: "2023-08-05",
      img: "../image/customer icon/men.png",
    },
    {
      customerID: "C009",
      customerNIC: "981234567V",
      fName: "Ruwan",
      lName: "Karunaratne",
      email: "ruwan.karunaratne@gmail.com",
      primaryContact: "0709012345",
      secondaryContact: "0769012345",
      address: "No. 10, Lake Road, Trincomalee",
      city: "Trincomalee",
      joinDate: "2023-09-12",
      img: "../image/customer icon/men.png",
    },
    {
      customerID: "C010",
      customerNIC: "991234567V",
      fName: "Pradeep",
      lName: "Ekanayake",
      email: "pradeep.ekanayake@gmail.com",
      primaryContact: "0710123456",
      secondaryContact: "0760123456",
      address: "No. 11, High Street, Jaffna",
      city: "Jaffna",
      joinDate: "2023-10-22",
      img: "../image/customer icon/men.png",
    },
  ],

  female: [
    {
      customerID: "C011",
      customerNIC: "902345678V",
      fName: "Nadeeka",
      lName: "Wijeratne",
      email: "nadeeka.wijeratne@gmail.com",
      primaryContact: "0771234567",
      secondaryContact: "0711234567",
      address: "No. 55, Lotus Street, Colombo 3",
      city: "Colombo",
      joinDate: "2023-01-10",
      img: "../image/customer icon/women.png",
    },
    {
      customerID: "C012",
      customerNIC: "912345678V",
      fName: "Shanika",
      lName: "Perera",
      email: "shanika.perera@gmail.com",
      primaryContact: "0772345678",
      secondaryContact: "0712345678",
      address: "No. 78, Hill Side, Kandy",
      city: "Kandy",
      joinDate: "2023-02-18",
      img: "../image/customer icon/women.png",
    },
    {
      customerID: "C013",
      customerNIC: "922345678V",
      fName: "Roshani",
      lName: "Fernando",
      email: "roshani.fernando@gmail.com",
      primaryContact: "0773456789",
      secondaryContact: "0713456789",
      address: "No. 23, Coastal Road, Galle",
      city: "Galle",
      joinDate: "2023-03-14",
      img: "../image/customer icon/women.png",
    },
    {
      customerID: "C014",
      customerNIC: "932345678V",
      fName: "Kavindi",
      lName: "Rajapaksha",
      email: "kavindi.rajapaksha@gmail.com",
      primaryContact: "0774567890",
      secondaryContact: "0714567890",
      address: "No. 67, Lake View, Nuwara Eliya",
      city: "Nuwara Eliya",
      joinDate: "2023-04-25",
      img: "../image/customer icon/women.png",
    },
    {
      customerID: "C015",
      customerNIC: "942345678V",
      fName: "Ruwandi",
      lName: "Gunasekara",
      email: "ruwandi.gunasekara@gmail.com",
      primaryContact: "0775678901",
      secondaryContact: "0715678901",
      address: "No. 34, Hill Top, Ratnapura",
      city: "Ratnapura",
      joinDate: "2023-05-20",
      img: "../image/customer icon/women.png",
    },
    {
      customerID: "C016",
      customerNIC: "952345678V",
      fName: "Gayathri",
      lName: "Abeysinghe",
      email: "gayathri.abeysinghe@gmail.com",
      primaryContact: "0776789012",
      secondaryContact: "0716789012",
      address: "No. 45, Circular Road, Matara",
      city: "Matara",
      joinDate: "2023-06-10",
      img: "../image/customer icon/women.png",
    },
    {
      customerID: "C017",
      customerNIC: "962345678V",
      fName: "Anoma",
      lName: "Kumari",
      email: "anoma.kumari@gmail.com",
      primaryContact: "0777890123",
      secondaryContact: "0717890123",
      address: "No. 90, Station Road, Kurunegala",
      city: "Kurunegala",
      joinDate: "2023-07-15",
      img: "../image/customer icon/women.png",
    },
    {
      customerID: "C018",
      customerNIC: "972345678V",
      fName: "Sanduni",
      lName: "Dissanayake",
      email: "sanduni.dissanayake@gmail.com",
      primaryContact: "0778901234",
      secondaryContact: "0718901234",
      address: "No. 21, Rose Avenue, Negombo",
      city: "Negombo",
      joinDate: "2023-08-01",
      img: "../image/customer icon/women.png",
    },
    {
      customerID: "C019",
      customerNIC: "982345678V",
      fName: "Dilini",
      lName: "Karunaratne",
      email: "dilini.karunaratne@gmail.com",
      primaryContact: "0779012345",
      secondaryContact: "0719012345",
      address: "No. 40, Palm Road, Trincomalee",
      city: "Trincomalee",
      joinDate: "2023-09-10",
      img: "../image/customer icon/women.png",
    },
    {
      customerID: "C020",
      customerNIC: "992345678V",
      fName: "Iresha",
      lName: "Ekanayake",
      email: "iresha.ekanayake@gmail.com",
      primaryContact: "0770123456",
      secondaryContact: "0710123456",
      address: "No. 31, Park Lane, Jaffna",
      city: "Jaffna",
      joinDate: "2023-10-20",
      img: "../image/customer icon/women.png",
    },
  ],
};

export function fetchCustomers() {
  readCustomersFromStorage();
  return customerData;
}

function readCustomersFromStorage() {
  const customerJSON = localStorage.getItem("customerData");
  if (customerJSON) {
    return JSON.parse(customerJSON);
  }
  return customerData;
}

export function addCustomer(customerObj, gender) {
  customerData[gender].push(customerObj);
  saveCustomersToStorage();
  console.log(customerData[gender]);
}

export function removeCustomer(index, gender) {
  console.log("remove ekata awa", index, gender);
  customerData[gender].splice(index, 1);
  saveCustomersToStorage();
  console.log(customerData[gender]);
}

function saveCustomersToStorage() {
  localStorage.setItem("customerData", JSON.stringify(customerData));
}
